# -*- coding: utf-8 -*-
"""M03-Projeto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IJdPN6Va1qWTeqd5vKWLSRmvycF9YT7J
"""

contas = []

def criar_conta():
  verificador_conta_existe = False
  dados_nova_conta = {}
  dados_nova_conta["numero_conta"] = input("Digite o numero da nova conta:\n>>> ")

  for conta_em_consulta in contas:
    if conta_em_consulta["numero_conta"] == dados_nova_conta["numero_conta"]:
      verificador_conta_existe = True
      break

  if verificador_conta_existe == True:
    print('\nO número da conta já existe. Tente novamente.')
  else:
    dados_nova_conta['saldo_conta'] = float(input('Digite o saldo da nova conta:\n>>> '))
    contas.append(dados_nova_conta)
    print('\nOperação efetuada com sucesso.')

def remover_conta():
  numero_conta = input('Digite o número da conta para remover:\n>>> ')
  conta_encontrada = False
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      conta_encontrada = True
      contas.remove(conta_em_consulta)
      print('\nOperação efetuada com sucesso.')
      break
  if not conta_encontrada:
    print('\nO número da conta não existe. Tente novamente.')


def listar_contas():
  if len(contas) == 0:
    print('\nNão há contas cadastradas.')
  else:
    index = 1
    for conta_em_consulta in contas:
      if conta_em_consulta["saldo_conta"] >= 0:
        status = "Positivo"
      else:
        status = "Negativo"
        #Obss: o pnto 2f aqui reduz a casa decimal para 2.
      print(f'{index} = Número da conta: {conta_em_consulta["numero_conta"]} | saldo da conta: R$ {conta_em_consulta["saldo_conta"]:.2f} ({status})')
      index += 1

def adicionar_saldo_em_conta():
  numero_conta = input('Digite o numero da conta:\n>>> ')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      valor_credito = float(input('Digite o valor do crédito:\n>>> R$'))
      if valor_credito < 0:
        print('\nValores negativos não são aceitos. Tente novamente.')
        return
      else:
        conta_em_consulta['saldo_conta'] += valor_credito
        print('\nOperação efetuada com sucesso.')
        return
  print('\no numero da conta não foi encontrado. Tente novamente.')

def remover_saldo_em_conta():
  numero_conta = input('Digite o numero da conta:\n>>> ')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      valor_debito = float(input('Digite o valor do débito:\n>>> R$'))
      if valor_debito < 0:
        print('\nValores negativos não são aceitos. Tente novamente.')
        return
      else:
        conta_em_consulta['saldo_conta'] -= valor_debito
        print('\nOperação efetuada com sucesso.')
        return
  print('\no numero da conta não foi encontrado. Tente novamente.')

def transferir_saldo_entre_conta():
  conta_partida = input('Digite o número da sua conta:\n>>> ')
  verificador_etapa = 0
  # verifica a primeira conta
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == conta_partida:
      verificador_etapa = 1
      conta_destino = input('Digite o número da conta destino:\n>>> ')
      if conta_destino != conta_partida:
        # procura segunda conta.
        for conta_destino_em_consulta in contas:
          if conta_destino_em_consulta['numero_conta'] == conta_destino:
            verificador_etapa = 3
            valor_transferencia = float(input('Digite o valor da transferência:\n>>> R$ '))
            #Verifica se o saldo é suficiente.
            if valor_transferencia < 0:
              print('\nNão é possível transferir um valor negativo.')
              break
            #Verifica se o valor é negativo.
            elif valor_transferencia > conta_em_consulta['saldo_conta']:
              print('\nNão é possível transferência um valor maior que seu saldo.')
              break
            else:
              conta_em_consulta['saldo_conta'] -= valor_transferencia
              conta_destino_em_consulta['saldo_conta'] += valor_transferencia
              print('\nOperação efetuada com sucesso.')
              break

        print()
      else:
        verificador_etapa = 2
        break

  if verificador_etapa == 0:
    print('\nA sua conta não foi encontrada. Tente novamente.')
  elif verificador_etapa == 1:
    print('\nA conta de destino não foi encontrada. Tente novamente.')
  elif verificador_etapa == 2:
    print('\nNão é possível transderir dinheiro para a mesma conta. Tente novamente.')

def consultar_saldo_de_conta():
  numero_conta = input('Digite o número da conta para consultar o saldo:\n>>> ')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      if conta_em_consulta["saldo_conta"] >= 0:
        status = "Positivo"
      else:
        status = "Negativo"
      print(f"\nO saldo é: R$ {conta_em_consulta['saldo_conta']:.2f} ({status})")
      return
  print('\nO númeero da conta não foi encontrado. Tente novamente.')
print(">>> Bem vindo ao sistema Bancário<<<")


while True:
  print("\n### Menu ###")
  print("0 - Sair")
  print("1 - Criar uma nova conta")
  print("2 - Remover uma conta")
  print("3 - Listar todas as contas")
  print("4 - Adicionar saldo (credita)")
  print("5 - Remover saldo (debitar)")
  print("6 - Transferir valor entre contas")
  print("7 - Consultar saldo de uma contas")
  numero_operacao = input("Selecione a operação que deseja realizar:\n>>> ")

  if numero_operacao == "0":
    print('\nSistema encerrado.')
    break

  # Operação 1 - Cria nova conta.
  elif numero_operacao == "1":
    criar_conta()

  # Operação 2 - Removee uma conta.
  elif numero_operacao == '2':
    remover_conta()

  # Operação 3 - Listar todas as contas.
  elif numero_operacao == '3':
    listar_contas()

  # Operação 4 - Adicionar saldo as contas.
  elif numero_operacao == '4':
    adicionar_saldo_em_conta()

  # Operação 5 - Remover saldo das contas.
  elif numero_operacao == '5':
    remover_saldo_em_conta()

  # Operação 6 - Transferir valor entre contas.
  elif numero_operacao == '6':
    transferir_saldo_entre_conta()
  # Operação 7 - Consultar saldo de uma conta.
  elif numero_operacao == '7':
    consultar_saldo_de_conta()

  else:
    print('\nOperaçao inválida.')